require:
  - 'rubocop-rspec'
  - 'rubocop-rails'

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vender/**/*
    - bin/**/*
  TargetRubyVersion: 3.1.1
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/*/*_spec.rb

Rails/FilePath:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either
